"""Add agent_id and segments table

Revision ID: e4e6f88cabb0
Revises: ca4b539aef90
Create Date: 2026-01-15 22:52:28.319839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e6f88cabb0'
down_revision: Union[str, None] = 'ca4b539aef90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
